### ISSUE TITLE
Unable to parse `Stale` with uppercase letter in Digest www-authenticate header

### ISSUE THREAD

**Issue by Drarig29** [nfroidure/http-auth-utils#21]
## Issue

I'm a gentledev I:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked I'm up to date with the latest version of the project

### Expected behavior

A www-authenticate header like `Digest realm="me@yahoo.com", nonce="fff", qop="auth", opaque="aaa", algorithm=MD5, Stale=FALSE` should be parseable. Postman and `curl` both support this.

### Actual behavior

Instead, we get the following error because the check with `AUTHORIZED_WWW_AUTHENTICATE_KEYS` is currently case-sensitive.
```
YError: E_UNAUTHORIZED_KEY (5, Stale)
```

### Steps to reproduce the behavior

```js
> const httpAuth = require('http-auth-utils')
> httpAuth.parseWWWAuthenticateHeader('Digest realm="me@yahoo.com", nonce="fff", qop="auth", opaque="aaa", algorithm=MD5, Stale=FALSE')
Uncaught YError: E_UNAUTHORIZED_KEY (5, Stale)
    at /project/node_modules/http-auth-utils/dist/utils.js:42:13
    at Array.reduce (<anonymous>)
    at parseHTTPHeadersQuotedKeyValueSet (/project/node_modules/http-auth-utils/dist/utils.js:40:6)
    at Object.parseWWWAuthenticateRest (/project/node_modules/http-auth-utils/dist/mechanisms/digest.js:62:57)
    at /project/node_modules/http-auth-utils/dist/index.js:105:29
    at Array.some (<anonymous>)
    at Object.parseWWWAuthenticateHeader (/project/node_modules/http-auth-utils/dist/index.js:101:18) {
  code: 'E_UNAUTHORIZED_KEY',
  params: [ 5, 'Stale' ],
  wrappedErrors: []
}
```

### Debugging informations
- `node -v` result:
```
v16.19.1
```

- `npm -v` result:
```
8.19.3
```

**Comment by nfroidure** [comment]
Same for here. I'll just check the RFC to be sure.

**Comment by Drarig29** [comment]
I think nothing in the RFC explicitly says it should be supported. But `curl` and Postman support it, so it should be OK to align with them.

**Comment by nfroidure** [comment]
In such cases where the support is wider then the standard I often add a "strict" option so that one that want to strictly apply standards may do it. That said, I think that if it is indeed in use in that way anywhere, the goal of this tool is to be usable so seems legit to support it.

**Comment by Drarig29** [comment]
@nfroidure cool. I made a PR for it.👌
