### ISSUE TITLE
Value for `stale` may not follow types in Digest www-authenticate header

### ISSUE THREAD

**Issue by Drarig29** [nfroidure/http-auth-utils#22]
## Issue

I'm a gentledev I:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked I'm up to date with the latest version of the project

### Expected behavior

If the www-authenticate header contains `stale=TRUE`, then the parsed value should be `stale: 'true'`, as the type below describes.

https://github.com/nfroidure/http-auth-utils/blob/a422b3577ee8eaebc8ec9e09a900d440980155f3/src/mechanisms/digest.ts#L26

According to https://www.rfc-editor.org/rfc/rfc2617#section-3.2.1, this value should be case-insensitive.

### Actual behavior

If the www-authenticate header contains `stale=TRUE`, then the parsed value stays the same: `stale: 'TRUE'`.

### Steps to reproduce the behavior

```js
> const httpAuth = require('http-auth-utils')
> httpAuth.parseWWWAuthenticateHeader('Digest realm="me@yahoo.com", nonce="fff", qop="auth", opaque="aaa", algorithm=MD5, stale=TRUE')
{
  type: 'Digest',
  data: {
    realm: 'me@yahoo.com',
    nonce: 'fff',
    qop: 'auth',
    opaque: 'aaa',
    algorithm: 'MD5',
    stale: 'TRUE'
  }
}
```

### Debugging informations
- `node -v` result:
```
v16.19.1
```

- `npm -v` result:
```
8.19.3
```

**Comment by nfroidure** [comment]
Seems legit. Feel free to PR or I'll do it myself asap.

**Comment by Drarig29** [comment]
Created this [draft PR](https://github.com/Drarig29/http-auth-utils/pull/1), for now on my fork because I based my branch on [this PR](https://github.com/nfroidure/http-auth-utils/pull/24).

And sadly, it's not possible to base a PR on a fork branch...

**Comment by nfroidure** [comment]
Looks like the charset/realm values are also case insensitive per the RFC so may be useful to lower case it too. Maybe that a new parameter named "caseInsensitiveParameters: []" could be added to `parseHTTPHeadersQuotedKeyValueSet` and then set in the various functions that use it depending on the RFC.

**Comment by Drarig29** [comment]
> Looks like the charset/realm values are also case insensitive per the RFC

Can you quote the part that says that? The only thing I find is in [1.2](https://www.rfc-editor.org/rfc/rfc2617#section-1.2):

> The realm directive (case-insensitive) is required for all authentication schemes that issue a challenge. The realm value (case-sensitive) [...]

**Comment by nfroidure** [comment]
Made a mistake, it says that the realm is case insensitive and its value case sensitive so your PR is ok.

There is another [occurrence of case insensivity here](https://www.ietf.org/rfc/rfc2617.html#section-1.2) :
![image](https://user-images.githubusercontent.com/229633/224000600-916c78c0-aecd-4d55-96df-bd860776a11b.png)

No idea where it is used.
