### ISSUE TITLE
Pre-flavored functions not available in typescript

### ISSUE THREAD

**Issue by leaumar** [nfroidure/http-auth-utils#4]
## Issue

I'm a gentledev I:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked I'm up to date with the latest version of the project

### Expected behavior

`BASIC.<functions>` can be used from typescript

### Actual behavior

Only `BASIC.type` is modeled by the types

### Debugging informations

Not really relevant, the published code just lacks the definitions either way:
```
type Mechanism = {
  type: string;
};

declare const BASIC: Mechanism;
```

**Comment by nfroidure** [comment]
Hi @leaumar , I plan to convert the whole plugin into TypeScript and then generate the types from it. In the meanwhile, I'm open to merge a quick fix. What would you suggest as a fix?

**Comment by leaumar** [comment]
I ended up not using this library so I'm not entirely familiar with the runtime values, but I think all it takes is to add the few function declarations to the const types like so

```typescript
declare const BASIC: Mechanism & {
    parseWWWAuthenticateRest: (rest: string) => Record<string, string>;
    // etc
};
```

**Comment by leaumar** [comment]
Awesome, thank you!
